-- Haradon factions and faction templates
-- Generated by NetCoreClient/tools/M425Patch from the 425 tables. Do not edit; re-run tools/build-m425.sh.
SET NAMES utf8mb4;

DELETE FROM `faction` WHERE `id` BETWEEN 1000 AND 1099;
DELETE FROM `faction_template` WHERE `id` BETWEEN 2000 AND 2099;

INSERT INTO `faction` (`id`,`build`,`reputation_list_id`,`base_rep_race_mask1`,`base_rep_race_mask2`,`base_rep_race_mask3`,`base_rep_race_mask4`,`base_rep_class_mask1`,`base_rep_class_mask2`,`base_rep_class_mask3`,`base_rep_class_mask4`,`base_rep_value1`,`base_rep_value2`,`base_rep_value3`,`base_rep_value4`,`reputation_flags1`,`reputation_flags2`,`reputation_flags3`,`reputation_flags4`,`team`,`name`,`description`) VALUES
(1000,4222,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'哈拉顿·光明','人类、精灵与蒙德尔人组成的光明阵营。'),
(1001,4222,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'哈拉顿·黑暗','兽人与亡灵组成的黑暗阵营。'),
(1002,4222,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'哈拉顿·敌对势力',''),
(1003,4222,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'哈拉顿·中立','');
INSERT INTO `faction_template` (`id`,`build`,`faction_id`,`faction_flags`,`our_mask`,`friendly_mask`,`hostile_mask`,`enemy_faction1`,`enemy_faction2`,`enemy_faction3`,`enemy_faction4`,`friend_faction1`,`friend_faction2`,`friend_faction3`,`friend_faction4`) VALUES
(2000,4222,1000,72,17,16,40,0,0,0,0,0,0,0,0),
(2001,4222,1001,72,33,32,24,0,0,0,0,0,0,0,0),
(2002,4222,1002,0,8,0,49,0,0,0,0,0,0,0,0),
(2003,4222,1003,0,0,49,0,0,0,0,0,0,0,0,0),
(2004,4222,1000,2081,16,16,40,0,0,0,0,0,0,0,0),
(2005,4222,1001,2081,32,32,24,0,0,0,0,0,0,0,0),
(2006,4222,1002,0,8,0,0,0,0,0,0,0,0,0,0);
