-- Caverns of Time <-> Middle Land portals
-- Generated by NetCoreClient/tools/M425Patch from the 425 tables. Do not edit; re-run tools/build-m425.sh.
SET NAMES utf8mb4;

DELETE FROM `spell_template` WHERE `entry` IN (39900, 39901);
DELETE FROM `spell_target_position` WHERE `id` IN (39900, 39901);
DELETE FROM `gameobject_template` WHERE `entry` IN (899900, 899901);
DELETE FROM `gameobject` WHERE `guid` IN (8999900, 8999901);

INSERT INTO `spell_target_position` (`id`,`target_map`,`target_position_x`,`target_position_y`,`target_position_z`,`target_orientation`,`build_min`,`build_max`) VALUES
(39900,604,2205,-2670,39.6,0.6,0,5875),
(39901,1,-8173.93,-4737.46,33.78,4.77,0,5875);
INSERT INTO `gameobject_template` (`entry`,`patch`,`type`,`displayId`,`name`,`faction`,`flags`,`size`,`data0`,`data1`,`data2`) VALUES
(899900,0,22,4396,'通往哈拉顿的传送门',35,0,1,39900,0,0);
INSERT INTO `gameobject` (`guid`,`id`,`map`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecsmin`,`spawntimesecsmax`,`animprogress`,`state`) VALUES
(8999900,899900,1,-8167,-4728,33.9,4.77,0,0,0.6864477,-0.72717917,0,0,100,1);
INSERT INTO `gameobject_template` (`entry`,`patch`,`type`,`displayId`,`name`,`faction`,`flags`,`size`,`data0`,`data1`,`data2`) VALUES
(899901,0,22,4396,'通往时光之穴的传送门',35,0,1,39901,0,0);
INSERT INTO `gameobject` (`guid`,`id`,`map`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecsmin`,`spawntimesecsmax`,`animprogress`,`state`) VALUES
(8999901,899901,604,2199,-2675,39.6,0.6,0,0,0.29552022,0.9553365,0,0,100,1);
DROP TEMPORARY TABLE IF EXISTS `m425_spell_copy`;
CREATE TEMPORARY TABLE `m425_spell_copy` SELECT * FROM `spell_template` WHERE `entry` = 25139 AND `build` = 4878;
UPDATE `m425_spell_copy` SET `entry` = 39900, `build` = 5875, `name` = '传送：哈拉顿', `description` = '', `auraDescription` = '', `effectImplicitTargetA1` = 1, `effectImplicitTargetB1` = 17;
INSERT INTO `spell_template` SELECT * FROM `m425_spell_copy`;
DROP TEMPORARY TABLE IF EXISTS `m425_spell_copy`;
CREATE TEMPORARY TABLE `m425_spell_copy` SELECT * FROM `spell_template` WHERE `entry` = 25139 AND `build` = 4878;
UPDATE `m425_spell_copy` SET `entry` = 39901, `build` = 5875, `name` = '传送：时光之穴', `description` = '', `auraDescription` = '', `effectImplicitTargetA1` = 1, `effectImplicitTargetB1` = 17;
INSERT INTO `spell_template` SELECT * FROM `m425_spell_copy`;
DROP TEMPORARY TABLE IF EXISTS `m425_spell_copy`;
