-- Removes every Haradon row (run tools/build-m425.sh --restore for the DBCs)
-- Generated by NetCoreClient/tools/M425Patch from the 425 tables. Do not edit; re-run tools/build-m425.sh.
SET NAMES utf8mb4;

DELETE FROM `map_template` WHERE `entry` BETWEEN 600 AND 699;
DELETE FROM `area_template` WHERE `entry` BETWEEN 4000 AND 6999;
DELETE FROM `game_graveyard_zone` WHERE `id` BETWEEN 5000 AND 5999;
DELETE FROM `world_safe_locs_facing` WHERE `id` BETWEEN 5000 AND 5999;
DELETE FROM `areatrigger_template` WHERE `id` BETWEEN 9000 AND 19999;
DELETE FROM `areatrigger_involvedrelation` WHERE `id` BETWEEN 9000 AND 19999;
DELETE FROM `game_tele` WHERE `name` LIKE 'm425\_%';
DELETE FROM `faction` WHERE `id` BETWEEN 1000 AND 1099;
DELETE FROM `faction_template` WHERE `id` BETWEEN 2000 AND 2099;
DELETE FROM `playercreateinfo` WHERE `race` BETWEEN 10 AND 14;
DELETE FROM `playercreateinfo_spell` WHERE `race` BETWEEN 10 AND 14;
DELETE FROM `playercreateinfo_item` WHERE `race` BETWEEN 10 AND 14;
DELETE FROM `playercreateinfo_action` WHERE `race` BETWEEN 10 AND 14;
DELETE FROM `player_levelstats` WHERE `race` BETWEEN 10 AND 14;
DELETE FROM `spell_template` WHERE `entry` BETWEEN 40000 AND 65535;
DELETE FROM `spell_target_position` WHERE `id` BETWEEN 40000 AND 65535;
DELETE FROM `item_template` WHERE `entry` BETWEEN 100000 AND 199999;
DELETE FROM `locales_item` WHERE `entry` BETWEEN 100000 AND 199999;
DELETE FROM `item_display_info` WHERE `ID` BETWEEN 50000 AND 99999;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `creature` WHERE `guid` BETWEEN 9000000 AND 9999999;
DELETE FROM `creature_display_info_addon` WHERE `display_id` BETWEEN 50000 AND 99999;
DELETE FROM `npc_vendor` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `creature_questrelation` WHERE `id` BETWEEN 900000 AND 999999;
DELETE FROM `creature_involvedrelation` WHERE `id` BETWEEN 900000 AND 999999;
DELETE FROM `gameobject_template` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `gameobject` WHERE `guid` BETWEEN 9000000 AND 9999999;
DELETE FROM `gameobject_questrelation` WHERE `id` BETWEEN 900000 AND 999999;
DELETE FROM `gameobject_involvedrelation` WHERE `id` BETWEEN 900000 AND 999999;
DELETE FROM `quest_template` WHERE `entry` BETWEEN 90000 AND 189999;
DELETE FROM `locales_quest` WHERE `entry` BETWEEN 90000 AND 189999;
DELETE FROM `areatrigger_involvedrelation` WHERE `quest` BETWEEN 90000 AND 189999;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 1000000 AND 1099999;
DELETE FROM `creature_loot_template` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `gameobject_loot_template` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `item_loot_template` WHERE `entry` BETWEEN 100000 AND 199999;
DELETE FROM `npc_text` WHERE `ID` BETWEEN 900000 AND 999999;
DELETE FROM `broadcast_text` WHERE `entry` BETWEEN 900000 AND 1099999;
DELETE FROM `npc_trainer` WHERE `entry` BETWEEN 900000 AND 999999;
DELETE FROM `spell_template` WHERE `entry` IN (39900, 39901);
DELETE FROM `spell_target_position` WHERE `id` IN (39900, 39901);
DELETE FROM `gameobject_template` WHERE `entry` IN (899900, 899901);
DELETE FROM `gameobject` WHERE `guid` IN (8999900, 8999901);
DROP TABLE IF EXISTS `m425_class`, `m425_classlevelstats`, `m425_xp_for_level`, `m425_appearance`, `m425_creature_stats`, `m425_automat`, `m425_script_text`, `m425_creature_script`, `m425_gameobject_trigger`, `m425_quest_script`, `m425_waypoint`, `m425_creature_waypoint`, `m425_map_script`, `m425_chat_menu`, `m425_creature_menu`, `m425_menu_variant`, `m425_menu_option`, `m425_talent`, `m425_talent_spell`;

